wxml_files = [
    'bxml/classBApplication.xml',
    'bxml/classBArchivable.xml',
    'bxml/classBHandler.xml',
    'bxml/classBLooper.xml',
    'bxml/classBMessage.xml',
    'bxml/classBPoint.xml',
    'bxml/classBRect.xml',
    'bxml/classBSize.xml',
    'bxml/classBWindow.xml',
]

[conditions]

[types]
[types.BMessage]
blocklist = [
    # Operator overload
    'operator=',
    'operator new',
    'operator new1',
    'operator new2',
    'operator delete',
    
    # Deprecated
    'FindInt322',
    
    # Rust doesn't support overload
    'AddFlat',
    'FindInt32',
]

[types.BPoint]
blocklist = [
    'operator=',
    'operator-',
    'operator+',
    'operator-1',
    'operator+=',
    'operator-=',
    'operator!=',
    'operator==',
]

[types.BRect]
blocklist = [
    'operator=',
    'operator==',
    'operator!=',
    'operator&',
    'operator|',
]

[types.BSize]
blocklist = [
    'operator==',
    'operator!=',
    'operator=',
    'Height',
    'SetHeight',
    'SetWidth',
    'Width',
]

[types.BWindow]
blocklist = [
    'ConvertFromScreen1',
    'ConvertFromScreen3',
    'ConvertToScreen1',
    'ConvertToScreen3',
]
