wxml_files = [
    'bxml/classBApplication.xml',
    'bxml/classBArchivable.xml',
    'bxml/classBHandler.xml',
    'bxml/classBLooper.xml',
    'bxml/classBMessage.xml',
    'bxml/classBSize.xml',
    'bxml/classBWindow.xml',
]

[conditions]

[types]
[types.BMessage]
blocklist = [
    # Operator overload
    'operator=',
    'operator new',
    'operator new1',
    'operator new2',
    'operator delete',
    
    # Deprecated
    'FindInt322',
    
    # Rust doesn't support overload
    'AddFlat',
    'FindInt32',
]

[types.BSize]
blocklist = [
    'operator==',
    'operator!=',
    'operator=',
]
