#include "generated.h"

// Including splitted source files into single source file to keep build.rs simple
#include "generated/ffi_a.cpp"
#include "generated/ffi_b.cpp"
#include "generated/ffi_c.cpp"
#include "generated/ffi_h.cpp"
#include "generated/ffi_i.cpp"
#include "generated/ffi_l.cpp"
#include "generated/ffi_m.cpp"
#include "generated/ffi_p.cpp"
#include "generated/ffi_r.cpp"
#include "generated/ffi_s.cpp"
#include "generated/ffi_v.cpp"
#include "generated/ffi_w.cpp"
